function pos = leg_pos(phi1,phi4)
%LEG_POS
%    POS = LEG_POS(PHI1,PHI4)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024-07-15 23:13:01

t2 = cos(phi1);
t3 = cos(phi4);
t4 = sin(phi1);
t5 = sin(phi4);
t6 = t2.*(3.7e+1./2.5e+2);
t7 = t3.*(3.7e+1./2.5e+2);
t8 = t4.*(3.7e+1./2.5e+2);
t9 = t5.*(3.7e+1./2.5e+2);
t12 = t2.*7.844e-2;
t13 = t3.*7.844e-2;
t14 = t4.*7.844e-2;
t15 = t5.*7.844e-2;
t10 = -t6;
t11 = -t9;
t16 = -t12;
t17 = -t14;
t18 = t8+t11;
t20 = t7+t10+7.0./5.0e+1;
t19 = t18.^2;
t21 = t20.^2;
t22 = t19.*2.809e-1;
t23 = t21.*2.809e-1;
t24 = t19+t21;
t25 = t24.^2;
t27 = t13+t16+t24+7.42e-2;
t26 = -t25;
t28 = 1.0./t27;
t29 = t22+t23+t26;
t30 = sqrt(t29);
t31 = t15+t17+t30;
t32 = t28.*t31;
t33 = atan(t32);
t34 = t33.*2.0;
t35 = cos(t34);
t36 = sin(t34);
t37 = t35.*(5.3e+1./2.0e+2);
pos = [sqrt((t8+t36.*(5.3e+1./2.0e+2)).^2+(t6+t37-7.0./1.0e+2).^2);pi./2.0-atan2(t4.*(3.7e+1./2.5e+2)+t36.*(5.3e+1./2.0e+2),t6+t37-7.0./1.0e+2)];
end
